models:
  - name: gpt-4o
    deployment_id: d4bf8b0e56fcf372
    temperature: 0
  - name: gpt-4o-mini
    deployment_id: d4bf8b0e56fcf372
    temperature: 0
  - name: gemini-1.0-pro
    deployment_id: d4bf8b0e56fcf372
    temperature: 0