[tool.poetry]
name = "doc_indexer"
version = "0.1.0"
description = "Indexes Kyma documents for RAG"
authors = []
package-mode = false

[tool.poetry.dependencies]
python = "~3.12"
hdbcli = "^2.22.29"
python-decouple = "^3.8"
generative-ai-hub-sdk = {extras = ["all"], version = "^4.0.0"}
python-dotenv = "^1.0.1"
unstructured = "^0.16.0"
markdown = "^3.7"
pydantic = "^2.9.2"

[tool.poetry.group.test.dependencies]
poethepoet = "^0.29.0"
black = "^24.10.0"
ruff = "^0.7.1"
mypy = "^1.13.0"
pytest = "^8.3.3"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
pythonpath = [
    "src"
]
testpaths = [
    "tests",
]

[tool.poe.tasks]
format = "black . --check"
lint = "ruff check ."
lint-fix = "ruff check . --fix"
format-fix = "black ."
typecheck = "mypy . --pretty --config-file ../mypy.ini"
codecheck = ["lint", "typecheck", "format"]
test-unit = "pytest tests/unit"
test-integration = "pytest tests/integration"
test = [
    "test-unit",
    "test-integration"
]